[package]
name = "gas-estimation"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
log = "0.4"
primitive-types = { version = "0.9", features = ["fp-conversion"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.6"
tokio = { version = "1.9", features = ["sync", "time"], optional = true }
tokio-tungstenite = { version = "0.15", features = ["native-tls"], optional = true }
tracing = "0.1"
url = "2.0"
web3 = { version = "0.17", default-features = false, optional = true }

[features]
tokio_ = ["tokio", "tokio-tungstenite"]
web3_ = ["web3", "primitive-types"]

[dev-dependencies]
assert_approx_eq = "1.1"
isahc = { version = "1.0", features = ["json"] }
mockall = "0.9"
serde_json = "1.0"
tokio = { version = "1.9", features = ["macros", "rt", "time"] }
tracing-subscriber = "0.2"
