[package]
name = "gas-estimation"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
log = "0.4"
primitive-types = { version = "0.9", features = ["fp-conversion"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.6"
web3 = { version = "0.16", default-features = false, optional = true }

[features]
web3_ = ["web3", "primitive-types"]

[dev-dependencies]
assert_approx_eq = "1.1"
isahc = { version = "1.0", features = ["json"] }
mockall = "0.9"
serde_json = "1.0"
